#!/bin/bash



chown root:wheel /usr/bin/GameGemNative
chmod 755 /usr/bin/GameGemNative

chown root:wheel /Library/LaunchDaemons/com.tyc.GameGemNative.plist
chmod 644 /Library/LaunchDaemons/com.tyc.GameGemNative.plist

killall GameGemiOS
killall GameGemNative

#clean files for old version.

if [ -d "/Applications/MemSearch.app" ];then
		rm -rf /Applications/MemSearch.app
fi
if [ -f "/usr/bin/tcscan" ];then
	rm /usr/bin/tcscan
fi
if [ -f "/Library/LaunchDaemons/com.tyc.tcscan.plist" ];then
	rm /Library/LaunchDaemons/com.tyc.tcscan.plist
fi

#/usr/bin/uicache
#  /bin/launchctl unload /Library/LaunchDaemons/com.tyc.GameGemNative.plist
/bin/launchctl load /Library/LaunchDaemons/com.tyc.GameGemNative.plist

/usr/bin/uicache

exit 0

