#!/bin/bash
dir=$(dirname "$0")
chown root:wheel /Applications/iGameGuardian.app/loader
chmod 6755 /Applications/iGameGuardian.app/loader

cp /Applications/iGameGuardian.app/gg_daemon.plist /Library/LaunchDaemons/
launchctl load -w /Library/LaunchDaemons/gg_daemon.plist

if [[ ! -d /var/mobile/Library/iGameGuardian ]]; then
    mkdir /var/mobile/Library/iGameGuardian
    chown mobile /var/mobile/Library/iGameGuardian
fi

uicache

exit 0
